extends Reference

enum{
	CMD_WAIT=0x00,
	CMD_FREQ=0x01, CMD_VEL, CMD_KEYON, CMD_KEYON_LEGATO, CMD_KEYON_STACCATO, CMD_KEYOFF,
	CMD_STOP, CMD_PAN, CMD_CLIP,
	CMD_ENABLE=0x20, CMD_MULT, CMD_DIV, CMD_DET, CMD_DETMODE, CMD_DUC,
	CMD_WAV, CMD_PAR, CMD_PAL, CMD_AR, CMD_PDR, CMD_PDL, CMD_DR, CMD_SL, CMD_SR, CMD_RR, CMD_RM, CMD_KSR,
	CMD_PM, CMD_OUT, CMD_PHI, CMD_DPHI, CMD_AMS, CMD_AML, CMD_FMS, CMD_FML,
	CMD_LFO_FREQ=0x40, CMD_LFO_WAVE, CMD_LFO_DUC, CMD_LFO_PHI
	CMD_DEBUG=0xFE,	CMD_END=0xFF
}
enum{
	FX_FRQ_SET=0x00, FX_FRQ_ADJ, FX_FRQ_SLIDE, FX_FRQ_PORTA, FX_ARPEGGIO,
	FX_FMI_SET, FX_FMI_ADJ, FX_FMI_SLIDE, FX_FMI_LFO,
	FX_MUL_SET, FX_DIV_SET,
	FX_DET_SET, FX_DET_ADJ, FX_DET_SLIDE,FX_ARP_SET,FX_ARP_SPEED
	FX_ATK_SET=0x10, FX_DEC_SET, FX_SUL_SET, FX_SUR_SET, FX_REL_SET,
	FX_KS_SET, FX_RPM_SET, FX_AMI_SET, FX_AMI_ADJ, FX_AMI_SLIDE, FX_AMI_LFO,
	FX_PAR_SET,FX_PAL_SET,FX_PDR_SET,FX_PDL_SET,
	FX_DLY_OFF=0x20, FX_DLY_CUT, FX_DLY_ON, FX_DLY_RETRIG, FX_DLY_PHI0,
	FX_RPT_ON, FX_RPT_RETRIG, FX_RPT_PHI0,
	FX_MOD_SET_MIN=0x30, FX_MOD_SET_MAX=0x33, FX_OUT_SET,
	FX_WAVE_SET, FX_DUC_SET, FX_PHI_SET,
	FX_LFO_WAVE_SET, FX_LFO_DUC_SET, FX_LFO_PHI_SET,
	FX_LFO_FREQ_SET, FX_LFO_FREQ_SET_HI, FX_LFO_FREQ_SET_LO,
	FX_CLIP_SET=0x3e,
	FX_DELAY=0x40, FX_DELAY_SONG, FX_GOTO_ORDER, FX_GOTO_NEXT,
	FX_TICKSROW_SET,FX_TICKSSEC_SET
	FX_DEBUG=0xFE,FX_END
}
enum{
	TRG_KEEP, TRG_ON, TRG_OFF, TRG_STOP
}

const MIN_FREQ:int=-200
const MAX_FREQ:int=14300
