extends Reference

enum{
	CMD_WAIT=0,
	CMD_DEBUG=254,
	CMD_END=255
}
const ATTRS=Pattern.ATTRS
const LG_MODE=Pattern.LEGATO_MODE
const DEFAULT_VOLUME:int=255
const DEFAULT_PAN:int=31
enum{
	SIG_DELAY_SONG,
	SIG_GOTO_ORDER,
	SIG_GOTO_NEXT,
	SIG_TICKS_SEC,
	SIG_TICKS_ROW,
	SIG_MAX
}
const MAX_WAIT_TIME:float=float(0x1000000)
