extends Reference
class_name ClampNodeConstants

enum {
	CLAMP_NONE,CLAMP_CLAMP,CLAMP_WRAP,CLAMP_BOUNCE,CLAMP_END
}
enum {
	CLAMP_NN,CLAMP_NC,CLAMP_NW,CLAMP_NB,
	CLAMP_CN=8,CLAMP_CC,CLAMP_CW,CLAMP_CB,
	CLAMP_WN=16,CLAMP_WC,CLAMP_WW,CLAMP_WB,
	CLAMP_BN=24,CLAMP_BC,CLAMP_BW,CLAMP_BB
}
const CLAMP_SHIFT:int=3
const STRINGS:Dictionary={
	CLAMP_NONE:"NODE_CLAMP_NONE",
	CLAMP_CLAMP:"NODE_CLAMP_CLAMP",
	CLAMP_WRAP:"NODE_CLAMP_WRAP",
	CLAMP_BOUNCE:"NODE_CLAMP_BOUNCE"
}

const AS_ARRAY:Array=[
	CLAMP_NONE,CLAMP_CLAMP,CLAMP_WRAP,CLAMP_BOUNCE
]
