extends Reference
class_name MapWaveNodeConstants

enum{
	LERP_NONE,LERP_LINEAR,LERP_COS,LERP_END
}

const LERP_STRINGS:Dictionary={
	LERP_NONE:"NODE_LERP_NONE",
	LERP_LINEAR:"NODE_LERP_LINEAR",
	LERP_COS:"NODE_LERP_COS",
}

const LERPS_AS_ARRAY:Array=[
	LERP_NONE,LERP_LINEAR,LERP_COS
]
