extends Reference
class_name MapWaveNodeConstants

enum{
	LERP_NONE,LERP_LINEAR,LERP_COS,LERP_END
}
enum{
	XERP_CONSTANT,XERP_EXTEND,XERP_WRAP,XERP_END
}

const LERP_STRINGS:Dictionary={
	LERP_NONE:"NODE_LERP_NONE",
	LERP_LINEAR:"NODE_LERP_LINEAR",
	LERP_COS:"NODE_LERP_COS",
}
const XERP_STRINGS:Dictionary={
	XERP_CONSTANT:"NODE_XERP_CONSTANT",
	XERP_EXTEND:"NODE_XERP_EXTEND",
	XERP_WRAP:"NODE_XERP_WRAP"
}
