extends Reference
class_name MixNodeConstants

enum {
	MIX_MIX,MIX_ADD,MIX_SUB,MIX_MUL,MIX_DIV,MIX_MOD,MIX_FMOD,
	MIX_POWER,MIX_MAX,MIX_MIN,MIX_CMP,MIX_SIGN_CP,MIX_END
}
const STRINGS:Dictionary={
	MIX_MIX:"NODE_MIX_MIX",
	MIX_ADD:"NODE_MIX_ADD",
	MIX_SUB:"NODE_MIX_SUB",
	MIX_MUL:"NODE_MIX_MUL",
	MIX_DIV:"NODE_MIX_DIV",
	MIX_MOD:"NODE_MIX_MOD",
	MIX_FMOD:"NODE_MIX_FMOD",
	MIX_POWER:"NODE_MIX_POW",
	MIX_MAX:"NODE_MIX_MAX",
	MIX_MIN:"NODE_MIX_MIN",
	MIX_CMP:"NODE_MIX_CMP",
	MIX_SIGN_CP:"NODE_MIX_SIGN_CP"
}

const AS_ARRAY:Array=[
	MIX_MIX,MIX_ADD,MIX_SUB,MIX_MUL,MIX_DIV,MIX_MOD,MIX_FMOD,
	MIX_POWER,MIX_MAX,MIX_MIN,MIX_SIGN_CP
]
